### ISSUE TITLE
Generating Gitlab CI configuration causes stack trace

### ISSUE THREAD

**Issue by gomesp** [pascalgrimaud/generator-jhipster-ci#17]
Thanks for the handy generator. I was testing the generation of a Gitlab CI config and I am getting the following stack trace (the monolith app that I created with default options did not have a .bowerrc file):

```
Welcome to the JHipster Continuous Integration Generator! v1.0.0

Reading the JHipster project configuration for your module
? Please choose your continuous integration: Gitlab-CI
   update .bowerrc

Unable to find .bowerrc. Reference to bowerrc parameter (key: allow_root, value:true) not added.

TypeError: this.debug is not a function
    at Object.addBowerrcParameter (/Users/gomesp/src/jhipster/node_modules/generator-jhipster/generators/generator-base.js:595:18)
    at child.writing (/Users/gomesp/src/jhipster/node_modules/generator-jhipster-ci/generators/app/index.js:97:26)
    at Object.<anonymous> (/Users/gomesp/src/jhipster/node_modules/yeoman-generator/lib/base.js:436:25)
    at /Users/gomesp/src/jhipster/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/gomesp/src/jhipster/node_modules/run-async/index.js:24:19
    at /Users/gomesp/src/jhipster/node_modules/yeoman-generator/lib/base.js:446:8
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

**Comment by pascalgrimaud** [comment]
hi @gomesp 

This module is not up-to-date and I'm pretty sure it's totally broken.
But the **Gitlab CI configuration** has been integrated to official generator-jhipster.  So you can use it directly:
`jhipster ci-cd`

Here the official documentation:
http://www.jhipster.tech/setting-up-ci/

And it's far better than this module :)

**Comment by gomesp** [comment]
Thanks. Closing the issue then as the alternative works fine. 👍

**Comment by pascalgrimaud** [comment]
you're welcome ;)
